dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/compress/mp.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py

Small speed up by yielding compressed data

Yield compressed data instead of wait fo all data processed

---

TODO.md
dedupsqlfs/__init__.py
dedupsqlfs/db/migration.py
dedupsqlfs/db/migrations/m20150712001.py
dedupsqlfs/db/mysql/table/subvolume.py
dedupsqlfs/db/sqlite/table/subvolume.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/fuse/snapshot.py
dedupsqlfs/fuse/subvolume.py

The goal is to store subvol stats after calculation. And recalculate if subvol was modified.
So:
1. Calc stats for ```@root``` subvol
2. Make snapshot
3. List subvols - stats wan't be calculated again

Recalculate subvol stats only if modified

---

dedupsqlfs/db/sqlite/table/hash.py
dedupsqlfs/db/sqlite/table/hash_compression_type.py
dedupsqlfs/db/sqlite/table/hash_sizes.py
dedupsqlfs/db/sqlite/table/inode.py
dedupsqlfs/db/sqlite/table/inode_hash_block.py
dedupsqlfs/db/sqlite/table/link.py
dedupsqlfs/db/sqlite/table/name.py
dedupsqlfs/db/sqlite/table/tmp_id_count.py
dedupsqlfs/db/sqlite/table/tree.py
dedupsqlfs/db/sqlite/table/xattr.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/subvolume.py

- use sets for search and generators for data from db
- don't use sqlite for hash counting
- get 20k rows at once from db

Speedup fs usage

---

dedupsqlfs/__init__.py
dedupsqlfs/app/do.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/subvolume.py
lib-dynload/zstd/src/fse.c
lib-dynload/zstd/src/fse.h
lib-dynload/zstd/src/fse_static.h
lib-dynload/zstd/src/python-zstd.c
lib-dynload/zstd/src/python-zstd.h
lib-dynload/zstd/src/zstd.c
lib-dynload/zstd/src/zstd.h
lib-dynload/zstd/src/zstd_static.h

- tree check don't needed after defragmentation
- update zstd module

Add skip tree check option for stats

---

dedupsqlfs/app/do.py
dedupsqlfs/db/mysql/__init__.py
dedupsqlfs/db/mysql/manager.py
dedupsqlfs/db/mysql/table/__init__.py
dedupsqlfs/db/mysql/table/block.py
dedupsqlfs/db/mysql/table/hash.py
dedupsqlfs/db/mysql/table/hash_compression_type.py
dedupsqlfs/db/mysql/table/hash_sizes.py
dedupsqlfs/db/mysql/table/inode.py
dedupsqlfs/db/mysql/table/inode_hash_block.py
dedupsqlfs/db/mysql/table/inode_option.py
dedupsqlfs/db/mysql/table/link.py
dedupsqlfs/db/mysql/table/name.py
dedupsqlfs/db/mysql/table/option.py
dedupsqlfs/db/mysql/table/subvolume.py
dedupsqlfs/db/mysql/table/tmp_ids.py
dedupsqlfs/db/mysql/table/tree.py
dedupsqlfs/db/mysql/table/xattr.py
dedupsqlfs/db/sqlite/manager.py
dedupsqlfs/db/sqlite/table/__init__.py
dedupsqlfs/db/sqlite/table/block.py
dedupsqlfs/db/sqlite/table/inode_option.py
dedupsqlfs/db/sqlite/table/tmp_id_count.py
dedupsqlfs/db/sqlite/table/tree.py
dedupsqlfs/fuse/dedupfs.py

- remove old unused code
- update table functions
- update default parameters for tables and server startup

Update MySQL support

---

lib-dynload/lz4/setup.py
lib-dynload/lzo/setup.py
lib-dynload/quicklz/setup.py
lib-dynload/quicklzb/setup.py
lib-dynload/quicklzf/setup.py
lib-dynload/quicklzm/setup.py
lib-dynload/snappy/setup.py
lib-dynload/zstd/setup.py

Setuptools deprecates

---

dedupsqlfs/app/mount.py
dedupsqlfs/fuse/operations.py

- don't GC hash and block records

Add new option for faster gc

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mount.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/operations.py

- reduce number of imported symbols
- reduce number of function calls
- fix profiling

Simple optimizations after profiling:

---

dedupsqlfs/app/do.py
dedupsqlfs/app/fsck.py
dedupsqlfs/app/mkfs.py
dedupsqlfs/app/mount.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/compress/mp.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py

- setup cpu limit for multiprocess compression
- setup single process (same as fuse) compression if cpu count <= 1
By request #48

Add CPU count limitation:

---

dedupsqlfs/db/mysql/table/tree.py
dedupsqlfs/db/sqlite/table/tree.py
dedupsqlfs/fuse/operations.py

- don't link-unlink - it's break the tree structure.
update tree node so it's points to another branch.
By request #53

Fix rename operation:

---

dedupsqlfs/app/mount.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py

 Add recompression on the fly for not currently selected compression methods.

---

dedupsqlfs/db/mysql/manager.py
dedupsqlfs/db/sqlite/manager.py
dedupsqlfs/db/sqlite/table/_base.py
dedupsqlfs/fuse/snapshot.py
dedupsqlfs/fuse/subvolume.py

- gzip table files after make snapshot
- ungzip/gzip on open/close - if was gzipped

Gzip snapshot table files

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mount.py
dedupsqlfs/db/mysql/manager.py
dedupsqlfs/db/sqlite/manager.py
dedupsqlfs/db/sqlite/table/_base.py
dedupsqlfs/fs.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/fuse/snapshot.py
dedupsqlfs/lib/constants.py

Parallel compressors may speedup half fs actions: pigz, pbzip2, pxz...
By #77 issue

Add support for many programs to compress sqlite files.

---

dedupsqlfs/__init__.py
dedupsqlfs/db/sqlite/table/_base.py

- fix loop break
- version info up

Add support for compression progs for sqlite3 files

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mount.py
dedupsqlfs/fuse/compress/mt.py
dedupsqlfs/fuse/dedupfs.py

Multi-threaded compression tool class

---

dedupsqlfs/compression/lz4r07.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/lib/cache/index.py
dedupsqlfs/lib/cache/inodes.py
dedupsqlfs/lib/cache/storage.py
dedupsqlfs/lib/constants.py

- don't update time for expired cache items
- don't drop cached data if it's just need to be flushed on disk
- expire by size and remove from cache oldest data, not newest
By issue #87

Change cache logic

---

README.md
bin/rebuild-all-compress-modules.sh
lib-dynload/lz4/setup.py
lib-dynload/lz4r07/setup.py
lib-dynload/lzma/setup.py
lib-dynload/lzo/setup.py
lib-dynload/quicklz/setup.py
lib-dynload/quicklzb/setup.py
lib-dynload/quicklzf/setup.py
lib-dynload/quicklzm/setup.py
lib-dynload/snappy/setup.py
lib-dynload/zstd/setup.py
lib-dynload/zstd001/setup.py
lib-dynload/zstd036/setup.py
lib-dynload/zstd047/setup.py
lib-dynload/zstd061/setup.py

Optimized setup scripts

---

dedupsqlfs/fuse/operations.py
dedupsqlfs/lib/cache/index.py
dedupsqlfs/lib/cache/inodes.py
dedupsqlfs/lib/cache/simple.py
dedupsqlfs/lib/cache/storage.py

First version of cache memory optimization:
- sets to tuples
- leaf dicts to lists
For issue #96

Cache memory optimizations

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mount.py
dedupsqlfs/argp.py
dedupsqlfs/compression/_base.py
dedupsqlfs/db/mysql/table/_base.py
dedupsqlfs/db/sqlite/manager.py
dedupsqlfs/db/sqlite/table/_base.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/lib/constants.py
tests/compression/level-timing-zstd.py

By #101 
- setup argparse help formater
- filter hash functions
- use `--compress` as main function to setup compression methods

Remove custom compression

---

dedupsqlfs/__init__.py
dedupsqlfs/db/migrations/m20170904001.py
dedupsqlfs/db/mysql/table/inode.py
dedupsqlfs/db/sqlite/table/inode.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/fuse/subvolume.py

- times are in BigInt type
- store times in nanoseconds
- migration
For #109

Store inode times in nanoseconds

---

dedupsqlfs/app/do.py
dedupsqlfs/app/fsck.py
dedupsqlfs/app/mkfs.py
dedupsqlfs/app/mount.py
dedupsqlfs/db/migrations/m20170909001.py
dedupsqlfs/db/mysql/table/inode_hash_block.py
dedupsqlfs/db/sqlite/table/inode_hash_block.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/lib/cache/index.py

For #108:
- update index table methods
- update fs operations
- add migration

Store block real size in index table

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mkfs.py
dedupsqlfs/app/mount.py
lib-dynload/lz4/__init__.py

Fail to mount if compression method not found

---

dedupsqlfs/dt.py
tests/cleanupplan/test-dates.py

- add 1 more distnance
- add new test for cleanup dates
By issue #88

Keep more snapshots

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mount.py
dedupsqlfs/db/migrations/m20171103001.py
dedupsqlfs/db/mysql/table/inode.py
dedupsqlfs/db/mysql/table/inode_hash_block.py
dedupsqlfs/db/mysql/table/subvolume.py
dedupsqlfs/db/mysql/table/tree.py
dedupsqlfs/db/sqlite/table/inode.py
dedupsqlfs/db/sqlite/table/inode_hash_block.py
dedupsqlfs/db/sqlite/table/subvolume.py
dedupsqlfs/db/sqlite/table/tree.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/fuse/subvolume.py
dedupsqlfs/my_formats.py

Calculate diff between subvol and root-vol

---

dedupsqlfs/fuse/operations.py

- fix `removexattr` log format
- add set new ctime in `removexattr` and `setxattr` if xattr changes
By #119 issue

Update inode ctime on xattrs update

---

dedupsqlfs/app/do.py
dedupsqlfs/fuse/subvolume.py

Count subvol/snapshot created today

---

dedupsqlfs/db/mysql/table/tree.py
dedupsqlfs/db/sqlite/table/tree.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/fuse/subvolume.py

- don't fetch all data from tree, only needed
- cache names

Speedup tree get children or relax sqlite load

---

dedupsqlfs/dt.py
tests/cleanupplan/test-dates.py

Use date ranges instead of calculations.
For #129

Fix snapshots cleanup by plan

---

dedupsqlfs/dt.py
tests/cleanupplan/test-dates.py

- days and weeks are 'day' intervals
- months and years - are calendar intervals
For #129

More precise intervals for pan cleanup

---

dedupsqlfs/db/sqlite/table/block.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/helpers/logger.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/fuse/snapshot.py
dedupsqlfs/fuse/subvolume.py

By issue #138 
- don't log anything if loglevel not enabled
- replace all calls to logger

Replace logger with custom class

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mkfs.py
dedupsqlfs/fuse/helpers/logger.py

For issue #143:
- add logs level reset function
- copy hash functions list code from mount

Fix fs usage report

---

dedupsqlfs/fuse/operations.py

- a little speedup link operation,
- add rollbacks on errors
For #151

Disable link to directory and more

---

dedupsqlfs/app/do.py
dedupsqlfs/app/fsck.py
dedupsqlfs/app/mkfs.py
dedupsqlfs/app/mount.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/proc.py

- add PID to lock-file - first line
- use one function to store lock message
- check if DB locked by US
- or locked and process gone
- exit from operations if DB is locked
For #82

New function to lock DB

---

dedupsqlfs/app/actions/__init__.py
dedupsqlfs/app/actions/rehash.py
dedupsqlfs/app/do.py
dedupsqlfs/fuse/operations.py

- rename hashing function in operations class, make it public
For #58

First variant of rehash action

---

dedupsqlfs/app/actions/recompress.py
dedupsqlfs/app/actions/rehash.py
dedupsqlfs/app/do.py
dedupsqlfs/db/mysql/table/subvolume.py
dedupsqlfs/db/sqlite/table/subvolume.py

Recompress action

---

README.md
dedupsqlfs/app/do.py
dedupsqlfs/app/mount.py
dedupsqlfs/compression/brotli.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/helpers/repr.py
dedupsqlfs/fuse/operations.py
setup.py

llfuse 1.x support

---

dedupsqlfs/fuse/operations.py
dedupsqlfs/lib/cache/index.py
dedupsqlfs/lib/cache/inodes.py
dedupsqlfs/lib/cache/simple.py
dedupsqlfs/lib/cache/storage.py

For #163 
Use objects with slots or recordclass if installed.

Use objects for cache

---

lib-dynload/zstd/MANIFEST.in
lib-dynload/zstd/PKG-INFO
lib-dynload/zstd/README.rst
lib-dynload/zstd/setup.py
lib-dynload/zstd/src/python-zstd.c
lib-dynload/zstd/src/python-zstd.h
lib-dynload/zstd/src/util.c
lib-dynload/zstd/src/util.h

Update python-zstd to 1.4.4.1 with multi-thread support

---

dedupsqlfs/lib/cache/index.py
dedupsqlfs/lib/cache/inodes.py
dedupsqlfs/lib/cache/simple.py
dedupsqlfs/lib/cache/storage.py

- use recordclass <= 0.12.1 or >= 0.13.0.1

Return back support of python3.4+

---

dedupsqlfs/app/actions/defragment.py
dedupsqlfs/app/actions/vacuum.py
dedupsqlfs/app/do.py
dedupsqlfs/app/fsck.py
dedupsqlfs/app/mount.py
dedupsqlfs/db/mysql/manager.py
dedupsqlfs/db/mysql/table/tmp_id_count.py
dedupsqlfs/db/mysql/table/tmp_ids.py
dedupsqlfs/db/sqlite/table/__init__.py
dedupsqlfs/db/sqlite/table/_memory.py
dedupsqlfs/db/sqlite/table/tmp_id_count.py
dedupsqlfs/db/sqlite/table/tmp_ids.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py

- remove GC completely from fuse operations
- move garbage colletor to defragment action
- move vacuum functions to vacuum action
- use memory tables for tmp
- fix DO command welcome output
- adjust mysql startup options
- remove useless gc command options

Updates for #175

---

dedupsqlfs/app/mount.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/lib/cache/simple.py
dedupsqlfs/lib/cache/storage.py

- and compression minimal size / ratio

For #180 - Adjust cache expiration times

---

dedupsqlfs/app/actions/vacuum.py

Save last vacuum time in options table

---

dedupsqlfs/app/actions/vacuum.py
dedupsqlfs/app/do.py

Add option to skip everyday vacuum if it was only X days ago

---

README.md
dedupsqlfs/db/sqlite/table/_base.py

Use more pragmas for sqlite table on dump-load process

---

dedupsqlfs/app/actions/vacuum.py
dedupsqlfs/db/sqlite/table/hash_sizes.py
dedupsqlfs/my_math.py

Append new algo for median calculation

---

dedupsqlfs/db/mysql/manager.py
dedupsqlfs/db/mysql/table/block.py
dedupsqlfs/db/mysql/table/hash.py
dedupsqlfs/db/mysql/table/name.py
dedupsqlfs/db/mysql/table/subvolume.py
dedupsqlfs/db/mysql/table/xattr.py
dedupsqlfs/fuse/operations.py

Wrong branch, but merge anyway

Finaly fix mysql db - hash value must be varbinary

---

dedupsqlfs/db/mysql/manager.py
dedupsqlfs/db/mysql/table/_base.py
dedupsqlfs/db/mysql/table/inode.py
dedupsqlfs/db/sqlite/table/inode.py

One more time fix mysqld statup and options, change one inode query

---

lib-dynload/_llfuse/Changes.rst
lib-dynload/_llfuse/PKG-INFO
lib-dynload/_llfuse/README.rst
lib-dynload/_llfuse/setup.cfg
lib-dynload/_llfuse/setup.py
lib-dynload/_llfuse/src/fuse_api.pxi
lib-dynload/_llfuse/src/handlers.pxi
lib-dynload/_llfuse/src/llfuse.c
lib-dynload/_llfuse/src/llfuse.pyx
lib-dynload/_llfuse/src/misc.pxi

Update should work with python 3.4

For issue #224 - update llfuse to 1.4.1

---

dedupsqlfs/app/do.py
dedupsqlfs/app/mkfs.py
dedupsqlfs/app/mount.py
dedupsqlfs/db/mysql/manager.py
dedupsqlfs/db/mysql/table/_base.py
dedupsqlfs/db/sqlite/manager.py
dedupsqlfs/db/sqlite/table/_base.py
dedupsqlfs/fuse/dedupfs.py
dedupsqlfs/fuse/operations.py
dedupsqlfs/lib/constants.py

And for common blocks (by hash)
- add support of zstdmt utility to compress subvolume table files
- add support of clustered data files for tables: block, hash, name, compression_type

For issue 219 - common/clustered tables for many backup nodes

---

dedupsqlfs/__init__.py
dedupsqlfs/app/mount.py
dedupsqlfs/db/sqlite/manager.py
dedupsqlfs/db/sqlite/table/_base.py
dedupsqlfs/fuse/compress/base.py
dedupsqlfs/fuse/operations.py

Add option to use sqlite memory tables

Fix compression method use: deflate
